version: "3"
services:
  web:
    build:
      context: .
    ports:
      - "5000:5000"
    networks:
      - mynetwork
  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge