name: Merge from Develop to Main

on:
  push:
    branches:
      - main

jobs:
  merge-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout main
          git merge --no-ff ${{ github.event.before }} --no-edit

      # Add your desired actions or commands here to execute after the merge
      # For example:
      - name: Build and Deploy
        run: |
          ./build.sh
          ./deploy.sh
